name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag project_h2o:$(date +%s)

    - name: Run Flutter tests
      run: docker run --rm project_h2o:$(date +%s) flutter test
